name: Check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
